package main

import (
	"fmt"
	"os"
	"path/filepath"
	"strings"
	"testing"
)

func TestExpandConfigCmd_OutputFormat(t *testing.T) {
	dir := t.TempDir()

	// Create .mkvdup.yaml files.
	writeTestYAML(t, filepath.Join(dir, "movies", "a.mkvdup.yaml"), `name: "a.mkv"
dedup_file: "/data/a.mkvdup"
source_dir: "/data/source"
`)
	writeTestYAML(t, filepath.Join(dir, "movies", "b.mkvdup.yaml"), `name: "b.mkv"
dedup_file: "/data/b.mkvdup"
source_dir: "/data/source"
`)

	// Create a standard config with includes glob.
	cfgPath := filepath.Join(dir, "mount.yaml")
	writeTestYAML(t, cfgPath, fmt.Sprintf(`includes:
  - "%s/movies/*.mkvdup.yaml"
`, dir))

	outPath := filepath.Join(dir, "expanded.yaml")
	oldQuiet := quiet
	quiet = true
	defer func() { quiet = oldQuiet }()

	if err := expandConfigCmd([]string{cfgPath}, false, outPath, false); err != nil {
		t.Fatalf("expandConfigCmd: %v", err)
	}

	data, err := os.ReadFile(outPath)
	if err != nil {
		t.Fatalf("read output: %v", err)
	}
	output := string(data)

	// Check header comments.
	if !strings.Contains(output, "# Auto-generated by: mkvdup expand-config") {
		t.Error("missing auto-generated header")
	}
	if !strings.Contains(output, "# Source:") {
		t.Error("missing source header")
	}
	if !strings.Contains(output, "# Generated:") {
		t.Error("missing generated timestamp header")
	}
	if !strings.Contains(output, "# Matched files: 2") {
		t.Error("missing or incorrect matched files count")
	}

	// Check includes format.
	if !strings.Contains(output, "includes:") {
		t.Error("output should use 'includes:' format")
	}

	// Check both files are listed.
	if !strings.Contains(output, "a.mkvdup.yaml") {
		t.Error("missing a.mkvdup.yaml in output")
	}
	if !strings.Contains(output, "b.mkvdup.yaml") {
		t.Error("missing b.mkvdup.yaml in output")
	}
}

func TestExpandConfigCmd_DryRun(t *testing.T) {
	dir := t.TempDir()

	writeTestYAML(t, filepath.Join(dir, "test.mkvdup.yaml"), `name: "test.mkv"
dedup_file: "/data/test.mkvdup"
source_dir: "/data/source"
`)
	cfgPath := filepath.Join(dir, "mount.yaml")
	writeTestYAML(t, cfgPath, fmt.Sprintf(`includes:
  - "%s/*.mkvdup.yaml"
`, dir))

	// --dry-run should not create a file.
	outPath := filepath.Join(dir, "should-not-exist.yaml")
	oldQuiet := quiet
	quiet = true
	defer func() { quiet = oldQuiet }()

	if err := expandConfigCmd([]string{cfgPath}, false, outPath, true); err != nil {
		t.Fatalf("expandConfigCmd --dry-run: %v", err)
	}

	if _, err := os.Stat(outPath); !os.IsNotExist(err) {
		t.Errorf("--dry-run should not create output file, but %s exists", outPath)
	}
}

func TestExpandConfigCmd_OutputWritesFile(t *testing.T) {
	dir := t.TempDir()

	writeTestYAML(t, filepath.Join(dir, "test.mkvdup.yaml"), `name: "test.mkv"
dedup_file: "/data/test.mkvdup"
source_dir: "/data/source"
`)
	cfgPath := filepath.Join(dir, "mount.yaml")
	writeTestYAML(t, cfgPath, fmt.Sprintf(`includes:
  - "%s/*.mkvdup.yaml"
`, dir))

	outPath := filepath.Join(dir, "expanded.yaml")
	oldQuiet := quiet
	quiet = true
	defer func() { quiet = oldQuiet }()

	if err := expandConfigCmd([]string{cfgPath}, false, outPath, false); err != nil {
		t.Fatalf("expandConfigCmd: %v", err)
	}

	if _, err := os.Stat(outPath); os.IsNotExist(err) {
		t.Fatal("--output should create the output file")
	}

	data, err := os.ReadFile(outPath)
	if err != nil {
		t.Fatalf("read output: %v", err)
	}
	if !strings.Contains(string(data), "test.mkvdup.yaml") {
		t.Error("output file should contain the matched file")
	}
}

func TestExpandConfigCmd_SkipsRewriteWhenUnchanged(t *testing.T) {
	dir := t.TempDir()

	writeTestYAML(t, filepath.Join(dir, "test.mkvdup.yaml"), `name: "test.mkv"
dedup_file: "/data/test.mkvdup"
source_dir: "/data/source"
`)
	cfgPath := filepath.Join(dir, "mount.yaml")
	writeTestYAML(t, cfgPath, fmt.Sprintf(`includes:
  - "%s/*.mkvdup.yaml"
`, dir))

	outPath := filepath.Join(dir, "expanded.yaml")
	oldQuiet := quiet
	quiet = true
	defer func() { quiet = oldQuiet }()

	// First run: creates the file.
	if err := expandConfigCmd([]string{cfgPath}, false, outPath, false); err != nil {
		t.Fatalf("first run: %v", err)
	}

	// Make the file read-only so that any attempted rewrite on the second run
	// would fail with a permission error. This makes the "no rewrite" behavior
	// deterministic and independent of timestamp precision in generated headers.
	if err := os.Chmod(outPath, 0444); err != nil {
		t.Fatalf("chmod read-only: %v", err)
	}

	// Second run with same inputs: should not attempt to rewrite, and thus
	// should still succeed even though the file is read-only.
	if err := expandConfigCmd([]string{cfgPath}, false, outPath, false); err != nil {
		t.Fatalf("second run: %v (file was likely rewritten despite unchanged includes)", err)
	}
}
