package main

import (
	"fmt"
	"os"
	"path/filepath"
	"strings"
	"time"

	"github.com/stuckj/mkvdup/internal/dedup"
)

// expandConfigCmd reads a config file (same format as mount/validate), resolves
// all includes glob patterns to explicit paths, and writes an expanded config
// that is semantically equivalent but with no wildcard patterns.
func expandConfigCmd(configPath string, outputPath string, dryRun bool) error {
	expanded, err := dedup.ExpandConfigFile(configPath)
	if err != nil {
		return err
	}

	// Add a generation header comment.
	absConfigPath, err := filepath.Abs(configPath)
	if err != nil {
		absConfigPath = configPath
	}

	var sb strings.Builder
	fmt.Fprintf(&sb, "# Auto-generated by: mkvdup expand-config\n")
	fmt.Fprintf(&sb, "# Source: %s\n", absConfigPath)
	fmt.Fprintf(&sb, "# Generated: %s\n", time.Now().UTC().Format(time.RFC3339))
	sb.Write(expanded)

	output := sb.String()

	if dryRun {
		fmt.Print(output)
		return nil
	}

	if outputPath == "" {
		fmt.Print(output)
		return nil
	}

	// Skip rewrite if the YAML content (non-comment lines) is unchanged,
	// to avoid triggering unnecessary mount reloads.
	if existing, err := os.ReadFile(outputPath); err == nil {
		if yamlContent(string(existing)) == yamlContent(output) {
			if !quiet {
				fmt.Fprintf(os.Stderr, "No changes to %s\n", outputPath)
			}
			return nil
		}
	}

	if err := os.WriteFile(outputPath, []byte(output), 0644); err != nil {
		return fmt.Errorf("write output file: %w", err)
	}

	absOutput, err := filepath.Abs(outputPath)
	if err != nil || absOutput == "" {
		absOutput = outputPath
	}
	if !quiet {
		fmt.Fprintf(os.Stderr, "Wrote %s\n", absOutput)
	}

	return nil
}

// yamlContent extracts the non-comment lines from a YAML string for comparison.
// This allows the header comments (timestamp, etc.) to change without triggering
// a rewrite when the actual config content is unchanged.
func yamlContent(s string) string {
	var lines []string
	for _, line := range strings.Split(s, "\n") {
		if !strings.HasPrefix(line, "#") {
			lines = append(lines, line)
		}
	}
	return strings.Join(lines, "\n")
}
