package main

import (
	"fmt"
	"os"
	"path/filepath"
	"strings"
	"testing"

	"github.com/stuckj/mkvdup/internal/dedup"
)

func TestExpandConfigCmd_OutputFormat(t *testing.T) {
	dir := t.TempDir()

	// Create .mkvdup.yaml files.
	writeTestYAML(t, filepath.Join(dir, "movies", "a.mkvdup.yaml"), `name: "a.mkv"
dedup_file: "/data/a.mkvdup"
source_dir: "/data/source"
`)
	writeTestYAML(t, filepath.Join(dir, "movies", "b.mkvdup.yaml"), `name: "b.mkv"
dedup_file: "/data/b.mkvdup"
source_dir: "/data/source"
`)

	// Create a standard config with includes glob.
	cfgPath := filepath.Join(dir, "mount.yaml")
	writeTestYAML(t, cfgPath, fmt.Sprintf(`includes:
  - "%s/movies/*.mkvdup.yaml"
`, dir))

	outPath := filepath.Join(dir, "expanded.yaml")
	oldQuiet := quiet
	quiet = true
	defer func() { quiet = oldQuiet }()

	if err := expandConfigCmd(cfgPath, outPath, false); err != nil {
		t.Fatalf("expandConfigCmd: %v", err)
	}

	data, err := os.ReadFile(outPath)
	if err != nil {
		t.Fatalf("read output: %v", err)
	}
	output := string(data)

	// Check header comments.
	if !strings.Contains(output, "# Auto-generated by: mkvdup expand-config") {
		t.Error("missing auto-generated header")
	}
	if !strings.Contains(output, "# Source:") {
		t.Error("missing source header")
	}
	if !strings.Contains(output, "# Generated:") {
		t.Error("missing generated timestamp header")
	}

	// Check includes format with explicit paths.
	if !strings.Contains(output, "includes:") {
		t.Error("output should contain 'includes:'")
	}
	if !strings.Contains(output, "a.mkvdup.yaml") {
		t.Error("missing a.mkvdup.yaml in output")
	}
	if !strings.Contains(output, "b.mkvdup.yaml") {
		t.Error("missing b.mkvdup.yaml in output")
	}
	// Should not contain glob patterns.
	if strings.Contains(output, "*.mkvdup.yaml") {
		t.Error("output should not contain glob patterns")
	}
}

func TestExpandConfigCmd_PreservesSettings(t *testing.T) {
	dir := t.TempDir()

	writeTestYAML(t, filepath.Join(dir, "movie.mkvdup.yaml"), `name: "movie.mkv"
dedup_file: "/data/movie.mkvdup"
source_dir: "/data/source"
`)

	// Config with on_error_command, virtual_files, and includes.
	cfgPath := filepath.Join(dir, "mount.yaml")
	writeTestYAML(t, cfgPath, fmt.Sprintf(`includes:
  - "%s/*.mkvdup.yaml"
virtual_files:
  - name: "inline.mkv"
    dedup_file: "/data/inline.mkvdup"
    source_dir: "/data/source"
on_error_command:
  command: ["curl", "-d", "%%source%%", "https://ntfy.sh/test"]
  timeout: 10s
`, dir))

	outPath := filepath.Join(dir, "expanded.yaml")
	oldQuiet := quiet
	quiet = true
	defer func() { quiet = oldQuiet }()

	if err := expandConfigCmd(cfgPath, outPath, false); err != nil {
		t.Fatalf("expandConfigCmd: %v", err)
	}

	data, err := os.ReadFile(outPath)
	if err != nil {
		t.Fatalf("read output: %v", err)
	}
	output := string(data)

	// All settings should be preserved.
	if !strings.Contains(output, "on_error_command:") {
		t.Error("on_error_command should be preserved")
	}
	if !strings.Contains(output, "virtual_files:") {
		t.Error("virtual_files should be preserved")
	}
	if !strings.Contains(output, "inline.mkv") {
		t.Error("virtual_files entry should be preserved")
	}
	if !strings.Contains(output, "ntfy.sh/test") {
		t.Error("on_error_command details should be preserved")
	}
	// Includes should be expanded (no glob).
	if !strings.Contains(output, "movie.mkvdup.yaml") {
		t.Error("expanded include should be present")
	}
	if strings.Contains(output, "*.mkvdup.yaml") {
		t.Error("glob pattern should not be in expanded output")
	}

	// Verify the expanded output is valid: it should be parseable by
	// ResolveConfigs (the same loader used by mount/validate/reload).
	// This catches schema regressions like missing MarshalYAML for
	// custom types (e.g., CommandValue).
	configs, errCmd, _, err := dedup.ResolveConfigs([]string{outPath})
	if err != nil {
		t.Fatalf("expanded config is not parseable by ResolveConfigs: %v", err)
	}
	if len(configs) < 2 {
		t.Errorf("expected at least 2 configs (1 included + 1 virtual_files), got %d", len(configs))
	}
	if errCmd == nil {
		t.Error("on_error_command should survive round-trip")
	}
}

func TestExpandConfigCmd_DryRun(t *testing.T) {
	dir := t.TempDir()

	writeTestYAML(t, filepath.Join(dir, "test.mkvdup.yaml"), `name: "test.mkv"
dedup_file: "/data/test.mkvdup"
source_dir: "/data/source"
`)
	cfgPath := filepath.Join(dir, "mount.yaml")
	writeTestYAML(t, cfgPath, fmt.Sprintf(`includes:
  - "%s/*.mkvdup.yaml"
`, dir))

	// --dry-run should not create a file.
	outPath := filepath.Join(dir, "should-not-exist.yaml")
	oldQuiet := quiet
	quiet = true
	defer func() { quiet = oldQuiet }()

	if err := expandConfigCmd(cfgPath, outPath, true); err != nil {
		t.Fatalf("expandConfigCmd --dry-run: %v", err)
	}

	if _, err := os.Stat(outPath); !os.IsNotExist(err) {
		t.Errorf("--dry-run should not create output file, but %s exists", outPath)
	}
}

func TestExpandConfigCmd_OutputWritesFile(t *testing.T) {
	dir := t.TempDir()

	writeTestYAML(t, filepath.Join(dir, "test.mkvdup.yaml"), `name: "test.mkv"
dedup_file: "/data/test.mkvdup"
source_dir: "/data/source"
`)
	cfgPath := filepath.Join(dir, "mount.yaml")
	writeTestYAML(t, cfgPath, fmt.Sprintf(`includes:
  - "%s/*.mkvdup.yaml"
`, dir))

	outPath := filepath.Join(dir, "expanded.yaml")
	oldQuiet := quiet
	quiet = true
	defer func() { quiet = oldQuiet }()

	if err := expandConfigCmd(cfgPath, outPath, false); err != nil {
		t.Fatalf("expandConfigCmd: %v", err)
	}

	if _, err := os.Stat(outPath); os.IsNotExist(err) {
		t.Fatal("--output should create the output file")
	}

	data, err := os.ReadFile(outPath)
	if err != nil {
		t.Fatalf("read output: %v", err)
	}
	if !strings.Contains(string(data), "test.mkvdup.yaml") {
		t.Error("output file should contain the matched file")
	}
}

func TestExpandConfigCmd_SkipsRewriteWhenUnchanged(t *testing.T) {
	dir := t.TempDir()

	writeTestYAML(t, filepath.Join(dir, "test.mkvdup.yaml"), `name: "test.mkv"
dedup_file: "/data/test.mkvdup"
source_dir: "/data/source"
`)
	cfgPath := filepath.Join(dir, "mount.yaml")
	writeTestYAML(t, cfgPath, fmt.Sprintf(`includes:
  - "%s/*.mkvdup.yaml"
`, dir))

	outPath := filepath.Join(dir, "expanded.yaml")
	oldQuiet := quiet
	quiet = true
	defer func() { quiet = oldQuiet }()

	// First run: creates the file.
	if err := expandConfigCmd(cfgPath, outPath, false); err != nil {
		t.Fatalf("first run: %v", err)
	}

	// Make the file read-only so that any attempted rewrite on the second run
	// would fail with a permission error.
	if err := os.Chmod(outPath, 0444); err != nil {
		t.Fatalf("chmod read-only: %v", err)
	}

	// Second run with same inputs: should not attempt to rewrite.
	if err := expandConfigCmd(cfgPath, outPath, false); err != nil {
		t.Fatalf("second run: %v (file was likely rewritten despite unchanged content)", err)
	}
}
