package main

import (
	"fmt"
	"os"
	"path/filepath"

	"github.com/stuckj/mkvdup/internal/dedup"
)

// relocateDedup moves an .mkvdup file and its .mkvdup.yaml sidecar to a new
// location, recalculating relative paths in the sidecar so they resolve to
// the same absolute locations from the new position.
func relocateDedup(src, dst string, force, dryRun bool) error {
	// Resolve source to absolute path
	absSrc, err := filepath.Abs(src)
	if err != nil {
		return fmt.Errorf("resolve source path: %w", err)
	}

	// Verify source .mkvdup file exists
	srcInfo, err := os.Stat(absSrc)
	if err != nil {
		return fmt.Errorf("source file: %w", err)
	}
	if srcInfo.IsDir() {
		return fmt.Errorf("source %s is a directory, expected an .mkvdup file", absSrc)
	}

	// Determine sidecar path
	sidecarSrc := absSrc + ".yaml"
	hasSidecar := true
	if _, err := os.Stat(sidecarSrc); os.IsNotExist(err) {
		hasSidecar = false
	} else if err != nil {
		return fmt.Errorf("check sidecar: %w", err)
	}

	// Resolve destination
	absDst, err := filepath.Abs(dst)
	if err != nil {
		return fmt.Errorf("resolve destination path: %w", err)
	}

	// If destination is an existing directory, or an explicitly-directory path
	// (e.g. ends with a path separator, like "/new/location/"), move into it
	// with the same filename.
	dstInfo, err := os.Stat(absDst)
	isDirDst := false
	if err == nil && dstInfo.IsDir() {
		isDirDst = true
	} else if os.IsNotExist(err) && len(dst) > 0 && os.IsPathSeparator(dst[len(dst)-1]) {
		isDirDst = true
	}
	if isDirDst {
		absDst = filepath.Join(absDst, filepath.Base(absSrc))
	}

	// Don't relocate to the same path
	if absSrc == absDst {
		return fmt.Errorf("source and destination are the same: %s", absSrc)
	}

	sidecarDst := absDst + ".yaml"

	// Check destination doesn't already exist (unless --force)
	if !force {
		if _, err := os.Stat(absDst); err == nil {
			return fmt.Errorf("destination %s already exists (use --force to overwrite)", absDst)
		}
		if hasSidecar {
			if _, err := os.Stat(sidecarDst); err == nil {
				return fmt.Errorf("destination sidecar %s already exists (use --force to overwrite)", sidecarDst)
			}
		}
	} else if !hasSidecar {
		// With --force, if the source has no sidecar but the destination does,
		// remove the stale destination sidecar so it doesn't become orphaned.
		if _, err := os.Stat(sidecarDst); err == nil {
			if !dryRun {
				if err := osRemove(sidecarDst); err != nil {
					return fmt.Errorf("remove stale destination sidecar %s: %w", sidecarDst, err)
				}
			}
		} else if !os.IsNotExist(err) {
			return fmt.Errorf("check destination sidecar %s: %w", sidecarDst, err)
		}
	}

	// Read and update sidecar if it exists
	var updatedSidecar []byte
	if hasSidecar {
		config, err := dedup.ReadConfig(sidecarSrc)
		if err != nil {
			return fmt.Errorf("read sidecar: %w", err)
		}

		srcDir := filepath.Dir(absSrc)
		dstDir := filepath.Dir(absDst)

		// dedup_file should point to the new location (since the .mkvdup file
		// itself is being moved). Use the basename for relative paths (sidecar
		// and dedup file are always in the same directory), or the new absolute
		// path if the original was absolute.
		var newDedupFile string
		if filepath.IsAbs(config.DedupFile) {
			newDedupFile = absDst
		} else {
			newDedupFile = filepath.Base(absDst)
		}

		// source_dir points to a static location — recalculate relative to new position
		newSourceDir, err := recalcRelativePath(srcDir, dstDir, config.SourceDir)
		if err != nil {
			return fmt.Errorf("recalculate source_dir path: %w", err)
		}

		// Validate that source_dir is still reachable from the new location
		absSourceDir := resolveRelPath(dstDir, newSourceDir)
		if _, err := os.Stat(absSourceDir); err != nil {
			return fmt.Errorf("source directory not reachable from new location: %s → %s: %w", newSourceDir, absSourceDir, err)
		}

		updatedSidecar = []byte(fmt.Sprintf(`# Auto-generated by mkvdup relocate
name: %q
dedup_file: %q
source_dir: %q
`, config.Name, newDedupFile, newSourceDir))
	}

	// Dry run: print what would happen and return
	if dryRun {
		printInfo("Would move:\n")
		printInfo("  %s → %s\n", absSrc, absDst)
		if hasSidecar {
			printInfo("  %s → %s\n", sidecarSrc, sidecarDst)
			printInfo("\nUpdated sidecar would contain:\n")
			printInfo("%s", string(updatedSidecar))
		}
		return nil
	}

	// Ensure destination directory exists
	dstDir := filepath.Dir(absDst)
	if err := os.MkdirAll(dstDir, 0755); err != nil {
		return fmt.Errorf("create destination directory: %w", err)
	}

	// Move the .mkvdup file
	if err := osRename(absSrc, absDst); err != nil {
		return fmt.Errorf("move dedup file: %w", err)
	}

	// Write updated sidecar at destination (then remove old one)
	if hasSidecar {
		if err := os.WriteFile(sidecarDst, updatedSidecar, 0644); err != nil {
			// Try to undo the .mkvdup move
			_ = osRename(absDst, absSrc)
			return fmt.Errorf("write sidecar: %w", err)
		}
		// Remove old sidecar (only if src and dst sidecars are different files)
		if sidecarSrc != sidecarDst {
			if err := osRemove(sidecarSrc); err != nil && !os.IsNotExist(err) {
				printWarn("Warning: could not remove old sidecar %s: %v\n", sidecarSrc, err)
			}
		}
	}

	printInfo("Moved:\n")
	printInfo("  %s → %s\n", absSrc, absDst)
	if hasSidecar {
		printInfo("  %s → %s\n", sidecarSrc, sidecarDst)
	}

	return nil
}

// recalcRelativePath takes a path (which may be relative to oldBase or absolute),
// resolves it to absolute, and returns it relative to newBase. If the original
// path was absolute, it is returned unchanged.
func recalcRelativePath(oldBase, newBase, path string) (string, error) {
	if filepath.IsAbs(path) {
		return path, nil
	}

	// Resolve to absolute using old base
	absPath := filepath.Join(oldBase, path)
	absPath = filepath.Clean(absPath)

	// Make relative to new base
	rel, err := filepath.Rel(newBase, absPath)
	if err != nil {
		return "", fmt.Errorf("make relative to %s: %w", newBase, err)
	}

	return rel, nil
}

// resolveRelPath resolves a path relative to baseDir. If already absolute, returns as-is.
func resolveRelPath(baseDir, path string) string {
	if filepath.IsAbs(path) {
		return path
	}
	return filepath.Clean(filepath.Join(baseDir, path))
}

// printRelocateUsage prints the usage for the relocate command.
func printRelocateUsage() {
	fmt.Print(`Usage: mkvdup relocate [options] <source.mkvdup> <destination>

Move an .mkvdup file and its .mkvdup.yaml sidecar to a new location,
updating relative paths in the sidecar so they resolve to the same
absolute locations from the new position.

Arguments:
    <source.mkvdup>  Path to the .mkvdup file to move
    <destination>    Destination path (file or directory)

Options:
    --dry-run  Preview changes without moving files
    --force    Overwrite destination if it already exists

If <destination> is an existing directory, the file is moved into that
directory with its original filename. Otherwise, <destination> is used
as the new file path.

The .mkvdup.yaml sidecar (if present) is moved alongside the .mkvdup
file. The dedup_file path is updated to reference the new .mkvdup
location. The source_dir path is recalculated so it resolves to the
same absolute location from the new position (absolute source_dir
paths are preserved unchanged).

After moving, the command validates that source directories referenced
by the sidecar are still reachable.

Examples:
    mkvdup relocate movie.mkvdup /new/location/movie.mkvdup
    mkvdup relocate movie.mkvdup /new/location/
    mkvdup relocate --dry-run movie.mkvdup /new/location/
    mkvdup relocate --force movie.mkvdup /new/location/movie.mkvdup
`)
}
