package main

import (
	"os"
	"path/filepath"
	"strings"
	"testing"
)

func writeTestFile(t *testing.T, path, content string) {
	t.Helper()
	if err := os.MkdirAll(filepath.Dir(path), 0755); err != nil {
		t.Fatalf("mkdir %s: %v", filepath.Dir(path), err)
	}
	if err := os.WriteFile(path, []byte(content), 0644); err != nil {
		t.Fatalf("write %s: %v", path, err)
	}
}

func TestExpandConfigCmd_OutputFormat(t *testing.T) {
	dir := t.TempDir()

	// Create .mkvdup.yaml files.
	writeTestFile(t, filepath.Join(dir, "movies", "a.mkvdup.yaml"), `name: "a.mkv"
dedup_file: "/data/a.mkvdup"
source_dir: "/data/source"
`)
	writeTestFile(t, filepath.Join(dir, "movies", "b.mkvdup.yaml"), `name: "b.mkv"
dedup_file: "/data/b.mkvdup"
source_dir: "/data/source"
`)

	// Create wildcard config.
	cfgPath := filepath.Join(dir, "wildcard.yaml")
	writeTestFile(t, cfgPath, `sources:
  - path: `+dir+`
    pattern: "**/*.mkvdup.yaml"
`)

	// Capture output by writing to a file via --output.
	outPath := filepath.Join(dir, "expanded.yaml")
	quiet = true
	defer func() { quiet = false }()

	if err := expandConfigCmd(cfgPath, outPath, false); err != nil {
		t.Fatalf("expandConfigCmd: %v", err)
	}

	data, err := os.ReadFile(outPath)
	if err != nil {
		t.Fatalf("read output: %v", err)
	}
	output := string(data)

	// Check header comments.
	if !strings.Contains(output, "# Auto-generated by: mkvdup expand-config") {
		t.Error("missing auto-generated header")
	}
	if !strings.Contains(output, "# Source:") {
		t.Error("missing source header")
	}
	if !strings.Contains(output, "# Generated:") {
		t.Error("missing generated timestamp header")
	}
	if !strings.Contains(output, "# Matched files: 2") {
		t.Error("missing or incorrect matched files count")
	}

	// Check includes format.
	if !strings.Contains(output, "includes:") {
		t.Error("output should use 'includes:' format")
	}
	if strings.Contains(output, "\nfiles:") {
		t.Error("output should not use 'files:' format")
	}

	// Check both files are listed.
	if !strings.Contains(output, "a.mkvdup.yaml") {
		t.Error("missing a.mkvdup.yaml in output")
	}
	if !strings.Contains(output, "b.mkvdup.yaml") {
		t.Error("missing b.mkvdup.yaml in output")
	}
}

func TestExpandConfigCmd_DryRun(t *testing.T) {
	dir := t.TempDir()

	writeTestFile(t, filepath.Join(dir, "test.mkvdup.yaml"), "name: test")
	cfgPath := filepath.Join(dir, "wildcard.yaml")
	writeTestFile(t, cfgPath, `sources:
  - path: `+dir+`
    pattern: "*.mkvdup.yaml"
`)

	// --dry-run should not create a file.
	outPath := filepath.Join(dir, "should-not-exist.yaml")
	quiet = true
	defer func() { quiet = false }()

	if err := expandConfigCmd(cfgPath, outPath, true); err != nil {
		t.Fatalf("expandConfigCmd --dry-run: %v", err)
	}

	if _, err := os.Stat(outPath); !os.IsNotExist(err) {
		t.Errorf("--dry-run should not create output file, but %s exists", outPath)
	}
}

func TestExpandConfigCmd_OutputWritesFile(t *testing.T) {
	dir := t.TempDir()

	writeTestFile(t, filepath.Join(dir, "test.mkvdup.yaml"), "name: test")
	cfgPath := filepath.Join(dir, "wildcard.yaml")
	writeTestFile(t, cfgPath, `sources:
  - path: `+dir+`
    pattern: "*.mkvdup.yaml"
`)

	outPath := filepath.Join(dir, "expanded.yaml")
	quiet = true
	defer func() { quiet = false }()

	if err := expandConfigCmd(cfgPath, outPath, false); err != nil {
		t.Fatalf("expandConfigCmd: %v", err)
	}

	if _, err := os.Stat(outPath); os.IsNotExist(err) {
		t.Fatal("--output should create the output file")
	}

	data, err := os.ReadFile(outPath)
	if err != nil {
		t.Fatalf("read output: %v", err)
	}
	if !strings.Contains(string(data), "test.mkvdup.yaml") {
		t.Error("output file should contain the matched file")
	}
}
