package main

import (
	"fmt"
	"os"
	"path/filepath"
	"strings"
	"time"

	"github.com/stuckj/mkvdup/internal/dedup"
)

// expandConfigCmd reads a wildcard config file, resolves all glob patterns,
// and writes an expanded config with each matched .mkvdup.yaml explicitly listed.
func expandConfigCmd(configPath string, outputPath string, dryRun bool) error {
	cfg, err := dedup.ReadExpandConfig(configPath)
	if err != nil {
		return err
	}

	files, err := dedup.ResolveExpandConfig(cfg)
	if err != nil {
		return err
	}

	if len(files) == 0 {
		printWarn("Warning: no .mkvdup.yaml files matched\n")
	}

	if !quiet {
		fmt.Fprintf(os.Stderr, "Resolved %d %s\n", len(files), plural(len(files), "file", "files"))
	}

	// Build the output YAML content
	absConfigPath, err := filepath.Abs(configPath)
	if err != nil {
		return fmt.Errorf("resolve config path: %w", err)
	}

	var sb strings.Builder
	fmt.Fprintf(&sb, "# Auto-generated by: mkvdup expand-config %s\n", filepath.Base(absConfigPath))
	fmt.Fprintf(&sb, "# Source: %s\n", absConfigPath)
	fmt.Fprintf(&sb, "# Generated: %s\n", time.Now().UTC().Format(time.RFC3339))
	fmt.Fprintf(&sb, "# Matched files: %d\n", len(files))

	if len(files) == 0 {
		sb.WriteString("includes: []\n")
	} else {
		sb.WriteString("includes:\n")
		for _, f := range files {
			fmt.Fprintf(&sb, "  - %q\n", f)
		}
	}

	output := sb.String()

	if dryRun {
		fmt.Print(output)
		return nil
	}

	// Determine output path
	if outputPath == "" {
		// Default: write to stdout
		fmt.Print(output)
		return nil
	}

	if err := os.WriteFile(outputPath, []byte(output), 0644); err != nil {
		return fmt.Errorf("write output file: %w", err)
	}

	if !quiet {
		fmt.Fprintf(os.Stderr, "Wrote %s\n", outputPath)
	}

	return nil
}
