package main

import (
	"fmt"
	"os"
	"path/filepath"
	"strings"
	"time"

	"github.com/stuckj/mkvdup/internal/dedup"
)

// yamlContent extracts the non-comment lines from a YAML string for comparison.
// This allows the header comments (timestamp, etc.) to change without triggering
// a rewrite when the actual includes list is unchanged.
func yamlContent(s string) string {
	var lines []string
	for _, line := range strings.Split(s, "\n") {
		if !strings.HasPrefix(line, "#") {
			lines = append(lines, line)
		}
	}
	return strings.Join(lines, "\n")
}

// expandConfigCmd reads config files (same format as mount/validate), resolves
// all includes glob patterns, and writes an expanded config with each matched
// .mkvdup.yaml explicitly listed.
func expandConfigCmd(configPaths []string, configDir bool, outputPath string, dryRun bool) error {
	resolved, err := resolveConfigPaths(configPaths, configDir)
	if err != nil {
		return err
	}

	files, err := dedup.ResolveIncludePaths(resolved)
	if err != nil {
		return err
	}

	if len(files) == 0 {
		printWarn("Warning: no config files matched\n")
	}

	if !quiet {
		fmt.Fprintf(os.Stderr, "Resolved %d %s\n", len(files), plural(len(files), "file", "files"))
	}

	// Build the output YAML content.
	sourceDesc := strings.Join(resolved, ", ")

	var sb strings.Builder
	fmt.Fprintf(&sb, "# Auto-generated by: mkvdup expand-config\n")
	fmt.Fprintf(&sb, "# Source: %s\n", sourceDesc)
	fmt.Fprintf(&sb, "# Generated: %s\n", time.Now().UTC().Format(time.RFC3339))
	fmt.Fprintf(&sb, "# Matched files: %d\n", len(files))

	if len(files) == 0 {
		sb.WriteString("includes: []\n")
	} else {
		sb.WriteString("includes:\n")
		for _, f := range files {
			fmt.Fprintf(&sb, "  - %q\n", f)
		}
	}

	output := sb.String()

	if dryRun {
		fmt.Print(output)
		return nil
	}

	if outputPath == "" {
		fmt.Print(output)
		return nil
	}

	// Skip rewrite if the includes list is unchanged, to avoid triggering
	// unnecessary mount reloads from the file watcher.
	if existing, err := os.ReadFile(outputPath); err == nil {
		if yamlContent(string(existing)) == yamlContent(output) {
			if !quiet {
				fmt.Fprintf(os.Stderr, "No changes to %s\n", outputPath)
			}
			return nil
		}
	}

	if err := os.WriteFile(outputPath, []byte(output), 0644); err != nil {
		return fmt.Errorf("write output file: %w", err)
	}

	absOutput, err := filepath.Abs(outputPath)
	if err != nil || absOutput == "" {
		absOutput = outputPath
	}
	if !quiet {
		fmt.Fprintf(os.Stderr, "Wrote %s\n", absOutput)
	}

	return nil
}
